package logging

const NEW_LOG_UPDATE = "NEW_LOG_UPDATE"

const (
	INFO  = "INFO"
	WARN  = "WARN"
	ERROR = "ERROR"
)

// the ops type constant
const (
	// EXPORT logging
	EXPORT_LOGGING_OPS = "EXPORT LOGGING"
	COPY_VALUE_OPS     = "COPY VALUE"
	IGNORE_FILE_OPS    = "IGNORE FILE"

	// BRANCH RELATED OPS
	GET_LATEST_BRANCH_INFO_OPS                   = "GET LATEST BRANCH INFO"
	CREATE_NEW_BRANCH_OPS                        = "CREATE NEW BRANCH"
	CREATE_NEW_BRANCH_AND_SWITCH_OPS             = "CREATE NEW BRANCH AND SWITCH"
	CREATE_NEW_BRANCH_BASED_ON_REMOTE_BRANCH_OPS = "CREATE NEW BRANCH BASED ON REMOTE BRANCH"
	CREATE_NEW_BRANCH_BASED_ON_COMMIT_HASH_OPS   = "CREATE NEW BRANCH BASED ON COMMIT HASH"
	STASH_ALL_FILE_OPS                           = "STASH ALL"
	STASH_INDIVIDUAL_FILE_OPS                    = "STASH INDIVIDUAL FILE"
	SWITCH_BRANCH_OPS                            = "SWITCH BRANCH"
	DELETE_LOCAL_BRANCH_OPS                      = "DELETE LOCAL BRANCH"
	RENAME_LOCAL_BRANCH_OPS                      = "RENAME LOCAL BRANCH"
	RETRIEVE_LATEST_REMOTE_BRANCH_INFO           = "RETRIEVE LATEST REMOTE BRANCH INFO"
	MERGE_BRANCH_OPS                             = "MERGE BRANCH"
	GIT_MERGE_WITH_SIGNING_OPS                   = "MERGE WITH SIGNING"

	// COMMIT RELATED OPS
	COMMIT_OPS                         = "COMMIT"
	COMMIT_WITH_SIGNING_OPS            = "COMMIT WITH SIGNING"
	AMEND_COMMIT_OPS                   = "AMEND COMMIT"
	AMEND_COMMIT_WITH_SIGNING_OPS      = "AMEND COMMIT WITH SIGNING"
	GET_LATEST_COMMIT_MSG_AND_DESC_OPS = "GET LATEST COMMIT MSG AND DESCRIPTION"
	GIT_PUSH_OPS                       = "GIT PUSH"
	GIT_PUSH_WITH_SIGNING_OPS          = "GIT PUSH WITH SIGNING"
	GIT_RESET_LATEST_COMMIT_OPS        = "GIT RESET LATEST COMMIT"
	GIT_RESET_TO_SELECTED_COMMIT_OPS   = "GIT RESET TO SELECTED COMMIT"

	// FILES RELATED OPS
	FILES_STATUS_OPS            = "FILES STATUS"
	FILE_DIFF_OPS               = "FILE DIFF"
	STAGE_OR_UNSTAGE_FILE_OPS   = "STAGE OR UNSTAGE FILE"
	STAGE_ALL_CHANGES_OPS       = "STAGE ALL CHANGES"
	UNSTAGE_ALL_CHANGES_OPS     = "UNSTAGE ALL CHANGES"
	STAGE_LINE_OPS              = "STAGE LINE"
	UNSTAGE_LINE_OPS            = "UNSTAGE LINE"
	DISCARD_FILE_CHANGES_OPS    = "DISCARD FILE CHANGES"
	DISCARD_LINE_CHANGES_OPS    = "DISCARD LINE CHANGES"
	RETRIEVE_ORIGINAL_FILE_OPS  = "RETRIEVE ORIGINAL FILE"
	REVERT_ORIGINAL_FILE_OPS    = "REVERT FILE"
	REVERT_NEWLY_NAMED_FILE_OPS = "REVERT NEWLY NAMED FILE"
	REMOVE_NEWLY_NAMED_FILE_OPS = "REMOVE NEWLY NAMED FILE"
	RESOLVE_CONFLICT_OPS        = "RESOLVE CONFLICT"

	// COMMIT LOG RELATED OPS
	COMMIT_LOG_OPS                 = "COMMIT LOG"
	COMMIT_LOG_DETAIL_OPS          = "COMMIT LOG DETAIL"
	CHERRY_PICK_COMMIT_OPS         = "CHERRY PICK COMMIT"
	CHERRY_PICK_WITH_SIGNING_OPS   = "CHERRY PICK WITH SIGNING"
	REVERT_COMMIT_OPS              = "REVERT COMMIT"
	REVERT_COMMIT_WITH_SIGNING_OPS = "REVERT COMMIT WITH SIGNING"
	CHECKOUT_COMMIT_FILE_OPS       = "CHECKOUT COMMIT FILE"
	DISCARD_COMMIT_FILE_OPS        = "DISCARD COMMIT FILE"

	// FETCH RELATED OPS
	FETCH_OPS = "FETCH_OPS"

	// PULL RELATED OPS
	PULL_OPS                    = "PULL"
	GIT_PULL_WITH_SIGNING_OPS   = "GIT PULL WITH SIGNING"
	REBASE_OPS                  = "REBASE"
	GIT_REBASE_WITH_SIGNING_OPS = "GIT REBASE WITH SIGNING"

	// REMOTE RELATED OPS
	ADD_REMOTE_OPS                      = "ADD REMOTE"
	REMOVE_REMOTE_OPS                   = "REMOVE REMOTE"
	CHANGE_REMOTE_NAME_OPS              = "CHANGE REMOTE NAME"
	CHANGE_REMOTE_URL_OPS               = "CHANGE REMOTE URL"
	CHECK_REMOTE_OPS                    = "CHECK REMOTE"
	CHECK_REMOTE_SYNC_STATUS_OPS        = "CHECK REMOTE SYNC STATUS"
	SET_REMOTE_AS_TRACKING_UPSTREAM_OPS = "SET SELECTED REMOTE AS TRACKING UPSTREAM REMOTE"

	// STASH RELATED OPS
	GET_STASH_INFO = "GET STASH INFO"
	STASH_ALL      = "STASH ALL"
	STASH_FILE     = "STASH FILE"
	STASH_APPLY    = "STASH APPLY"
	STASH_POP      = "STASH POP"
	STASH_DROP     = "STASH DROP"
	STASH_DETAIL   = "STASH DETAIL"

	// UNIVERSAL STATE OPS
	SKIP                             = "SKIP"
	ABORT                            = "ABORT"
	CONTINUE                         = "CONTINUE"
	CONTINUE_COMMIT_WITH_SIGNING_OPS = "CONTINUE COMMIT WITH SIGNING"

	// ACQUIRE GIT LOCK
	ACQUIRE_GIT_LOCK = "ACQUIRE_GIT_LOCK"

	// GIT TAG RELATED OPS
	GET_LATEST_TAG_INFO_OPS            = "GET LATEST TAG INFO"
	CREATE_NEW_TAG_OPS                 = "CREATE NEW TAG"
	CREATE_NEW_TAG_WITH_SIGNING_OPS    = "CREATE NEW TAG WITH SIGNING"
	TAG_DETAIL_OPS                     = "TAG DETAIL"
	TAG_PUSH_OPS                       = "TAG PUSH"
	TAG_PUSH_WITH_SIGNING_OPS          = "TAG PUSH WITH SIGNING"
	TAG_FETCH_OPS                      = "TAG FETCH"
	TAG_DELETE_OPS                     = "TAG DELETE"
	TAG_REMOTE_DELETE_WITH_SIGNING_OPS = "TAG REMOTE DELETE WITH SIGNING"
	CHECKOUT_TAG_OPS                   = "CHECKOUT TAG"

	// GIT BLAME RELATED OPS
	GET_CURRENT_GIT_TRACKED_FILES = "GET_CURRENT_GIT_TRACKED_FILES"
	GET_FILE_BLAME_INFO           = "GET_FILE_BLAME_INFO"

	// INTERACTIVE REBASE
	INTERACTIVE_REBASE_FIXUP_SQUASH = "INTERACTIVE REBASE FIXUP/SQUASH"
	INTERACTIVE_REBASE_REWORD       = "INTERACTIVE REBASE REWORD"
	INTERACTIVE_REBASE_DROP         = "INTERACTIVE REBASE DROP"

	// WORKTREE
	GET_LATEST_WORKTREE_INFO = "GET_LATEST_WORKTREE_INFO"
	ADD_NEW_WORKTREE_OPS     = "ADD_NEW_WORKTREE_OPS"
	REMOVE_WORKTREE_OPS      = "REMOVE_WORKTREE_OPS"
	PRUNE_WORKTREES_OPS      = "PRUNE_WORKTREES_OPS"
	LOCK_WORKTREE_OPS        = "LOCK_WORKTREE_OPS"
	UNLOCK_WORKTREE_OPS      = "UNLOCK_WORKTREE_OPS"
	SWITCH_WORKTREE_OPS      = "SWITCH_WORKTREE_OPS"
)
